import React from 'react'
import NowPlayingMovies from './components/NowPlayingMovies'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Movie | Now Playing",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <NowPlayingMovies />
  )
}

export default Page