import React from 'react'
import Airing from './components/Airing'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Tv | Airing Today",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <Airing />
  )
}

export default Page