import Sidebar from "@/components/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import { GlobalProviders } from "../context/GlobalContext";
import Dialog from "@/components/Dialog";
import SearchBar from "@/components/SearchBar";
import Providers from "@/utils/Providers";
import { ErrorBoundary } from "react-error-boundary";
import NotFound from "./not-found";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TMDB App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <GlobalProviders>
            <Dialog />
            <Sidebar />
            <SearchBar />
            <ErrorBoundary fallback={<NotFound />}>
              <Header />
              {children}
            </ErrorBoundary>
          </GlobalProviders>
        </Providers>
      </body>
    </html>
  );
}
