import React from 'react'
import PopularTv from './components/PopulatTv'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Movie | Popular Tv",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <PopularTv />
  )
}

export default Page