import React from 'react'
import TopRatedTv from './components/TopRatedTv'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Tv | Top Rated",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <TopRatedTv />
  )
}

export default Page