import { Metadata } from 'next';
import React from 'react'
import TopRatedMovies from './components/TopRatedMovies';

export const metadata: Metadata = {
  title: "Movie | Top Rated",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <TopRatedMovies />
  )
}

export default Page