import React from 'react'
import Upcoming from './components/Upcoming'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Movie | Popular",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <Upcoming />
  )
}

export default Page